substitutions:
  name: m5stack-atom-echo-b70634
  friendly_name: Bedroom Atom Echo b70634
packages:
  m5stack.atom-echo: github://esphome/firmware/media-player/m5stack-atom-echo.yaml@main
esphome:
  name: ${name}
  name_add_mac_suffix: false
  friendly_name: ${friendly_name}


# Wifi information
wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password
  fast_connect: true
  ap:
    ssid: ${name}
    password: ${name}

captive_portal:

# Enable Home Assistant API
api:

ota:

# Enable logging
logger:
