###############################################################################
# BASE DEVICE CONFIG ##########################################################
###############################################################################

substitutions:
  name: esp32-s3-box-3-5a7854
  friendly_name: Study S3 Voice 5a7854
  micro_wake_word_model: hey_jarvis
packages:
  esphome.voice-assistant: github://esphome/firmware/wake-word-voice-assistant/esp32-s3-box-3.yaml@main
esphome:
  name: ${name}
  name_add_mac_suffix: false
  friendly_name: ${friendly_name}

###############################################################################

# Wifi information
wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password
  ap:
    ssid: ${name}
    password: ${name}

# Enable Home Assistant API
api:
  encryption:
    key: lVB3Eddi7iRL1fYdX5PHH/0htdZgPkOCMZbuAWlgTgc=
ota:
  password: bFv/mB1BNQOGNe/NH6p3gBPpua92F82BMMOh2jCy5bc=
  
# Enable logging
logger:

###############################################################################