###############################################################################
# BASE DEVICE CONFIG ##########################################################
###############################################################################

substitutions:
  name: m5stack-atom-lite-315bd0
  friendly_name: Study Atom Speaker 315bd0
packages:
  m5stack.atom-speaker-kit: github://esphome/firmware/media-player/m5stack-atom-speaker-kit.yaml@main
esphome:
  name: ${name}
  name_add_mac_suffix: false
  friendly_name: ${friendly_name}

###############################################################################

# Wifi information
wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password
  fast_connect: true
  ap:
    ssid: ${name}
    password: ${name}

# Enable Home Assistant API
api:
  encryption:
    key: PDqaggnKXPtyz2GE4WA8j/kFTvauCuZ9kdugv4CRZUM=
ota:
  password: 9bANiFOqgVV/EtH8AlZ+K0CZ29T/+mBwcVdfxoGE0VI=

# Enable logging
logger:

###############################################################################
