###############################################################################
# BASE DEVICE CONFIG ##########################################################
###############################################################################

substitutions:
  name: waveshare-test-595fac
  friendly_name: WaveShare Test 595fac

esphome:
  name: ${name}
  friendly_name: ${friendly_name}
  name_add_mac_suffix: false
  platformio_options:
    board_build.flash_mode: dio
  on_boot:
      priority: 200.0
      then:
        - binary_sensor.template.publish:
            id: tof_near
            state: OFF
        - binary_sensor.template.publish:
            id: tof_mid
            state: OFF

esp32:
  board: esp32-s3-devkitc-1
  variant: esp32s3
  framework:
    type: esp-idf
    version: recommended
    sdkconfig_options:
      CONFIG_ESP32_S3_BOX_BOARD: "y"
   
psram:
  mode: quad
  speed: 80MHz

# https://www.waveshare.com/wiki/ESP32-S3-Zero
# https://files.waveshare.com/wiki/ESP32-S3-Zero/ESP32-S3-Zero-Sch.pdf
# https://esphome.io/components/sensor/tof10120
# https://esphome.io/components/i2c#i2c

i2c:
  sda: GPIO1
  scl: GPIO2
  scan: true
  id: bus_a

################################################################################

# Wifi information
wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password
  fast_connect: true

  # Enable fallback hotspot (captive portal) in case wifi connection fails
  ap:
    ssid: ${name}
    password: ${name}

captive_portal:

# Enable Home Assistant API
api:

ota:

# Enable logging
logger:

###############################################################################
# INPUTS & OUTPUTS ############################################################
###############################################################################

output:
  - platform: gpio
    pin:
      number: GPIO21
      mode: output
    id: LED

###############################################################################
# VARIABLES & SCRIPTS #########################################################
###############################################################################

globals:
  - id: cpu_speed
    type: int
    restore_value: no
    initial_value: "0"

time:
  - platform: homeassistant
    id: homeassistant_time
    on_time:
      - seconds: 0
        minutes: /1
        then:
          - output.turn_on: LED
          - delay: 250ms
          - output.turn_off: LED


###############################################################################
# HOME ASSISTANT BUTTONS ######################################################
###############################################################################

#Exposes control buttons
button:
  - platform: restart
    icon: mdi:power-cycle
    name: "ESP Reboot"

  - platform: factory_reset
    disabled_by_default: True
    name: "Factory Reset ESP"
    id: factory_reset_all

###############################################################################
# SENSORS #####################################################################
###############################################################################

binary_sensor:
  - platform: template
    name: "TOF Near"
    id: tof_near
  - platform: template
    name: "TOF Mid"
    id: tof_mid

###############################################################################

#text_sensor:

###############################################################################

# https://www.electroniclinic.com/wp-content/uploads/2020/11/TOF10120-Datasheet.pdf
# RangeFinder supports both the UART and the I2C communication
# Pin number1 is the ground.
# Pin number2 is the VDD.
# Pin number3 is the RXD.
# Pin number4 is the TXD.
# Pin number 5 is the SDA
# Pin number6 is the SCL.
# Out of the 6 pins of the TOF10120 I will use only 4 pins. GND, VDD, SDA, and SCL.

# TOF10120 I2C Address:
# As per the datasheet the I2C address of the TOF10120 is 0xA4.
# But i2c addressing uses the high 7 bits so it’s 0x52 which is equivalent to 82.
# You can also find the I2C address of the TOF10120 by using the I2C Scanner code which is available below in the programming section.

sensor:
  # - platform: tof10120
  #   name: "TOF10120 Distance"
  #   update_interval: 5s
  #   on_value_range:
  #     - below: 200.0
  #       then:
  #         - binary_sensor.template.publish:
  #             id: tof_near
  #             state: ON
  #         - binary_sensor.template.publish:
  #             id: tof_mid
  #             state: OFF
  #     - above: 200.0
  #       below: 500.0
  #       then:
  #         - binary_sensor.template.publish:
  #             id: tof_near
  #             state: OFF
  #         - binary_sensor.template.publish:
  #             id: tof_mid
  #             state: ON
  #     - above: 500.0
  #       then:
 


    #Device UPTIME
  - platform: uptime
    name: Uptime
    id: sys_uptime
    update_interval: 60s

    #Device CPU Speed
  - platform: template
    name: "ESP Cpu Speed"
    accuracy_decimals: 0
    unit_of_measurement: Mhz
    lambda: |-
      return (id(cpu_speed));
    entity_category: "diagnostic"

    #Device Memory
  - platform: template
    id: esp_memory
    icon: mdi:memory
    name: ESP Free Memory
    lambda: return heap_caps_get_free_size(MALLOC_CAP_INTERNAL) / 1024;
    unit_of_measurement: "kB"
    state_class: measurement
    entity_category: "diagnostic"

    #Device RSSI
  - platform: wifi_signal
    name: RSSI
    id: wifi_signal_db
    update_interval: 60s
    entity_category: "diagnostic"

################################################################################

