###############################################################################
# NOTES #######################################################################
###############################################################################

# https://www.waveshare.com/wiki/ESP32-S3-Zero
# https://files.waveshare.com/wiki/ESP32-S3-Zero/ESP32-S3-Zero-Sch.pdf

# https://esphome.io/components/i2c
# https://esphome.io/components/uart

# https://esphome.io/components/sensor/ld2420

###############################################################################
# BASE DEVICE CONFIG ##########################################################
###############################################################################

substitutions:
  name: waveshare-test-595fac
  friendly_name: WaveShare Zero LD2420 595fac

esphome:
  name: ${name}
  friendly_name: ${friendly_name}
  name_add_mac_suffix: false
  platformio_options:
    board_build.flash_mode: dio
  on_boot:
      priority: 200.0
      then:
        - binary_sensor.template.publish:
            id: tof_near
            state: OFF
        - binary_sensor.template.publish:
            id: tof_mid
            state: OFF

esp32:
  board: esp32-s3-devkitc-1
  variant: esp32s3
  framework:
    type: esp-idf
    version: recommended
    sdkconfig_options:
      CONFIG_ESP32_S3_BOX_BOARD: "y"
   
psram:
  mode: quad
  speed: 80MHz

################################################################################

# Wifi information
wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password
  ap:
    ssid: ${name}
    password: ${name}

captive_portal:

# Enable Home Assistant API
api:
  encryption:
    key: FtxZJUW5UnYAXtdnnvAPgS/z7DlSP1ixst114hwFL+k=
ota:
  platform: esphome
#  password: FtxZJUW5UnYAXtdnnvAPgS/z7DlSP1ixst114hwFL+k=

# Enable logging
logger:

###############################################################################
# INPUTS & OUTPUTS ############################################################
###############################################################################

i2c:
  sda: GPIO01
  scl: GPIO02
  scan: true
  id: bus_a

# uart:
#   tx_pin: GPIO43
#   rx_pin: GPIO44
#   baud_rate: 115200

uart:
  id: ld2420_uart
  tx_pin: GPIO13
  rx_pin: GPIO12
  baud_rate: 115200
  parity: NONE
  stop_bits: 1

output:
  - platform: gpio
    pin:
      number: GPIO21
      mode: output
    id: LED

ld2420:

###############################################################################
# VARIABLES & SCRIPTS #########################################################
###############################################################################

globals:
  - id: cpu_speed
    type: int
    restore_value: no
    initial_value: "0"

time:
  - platform: homeassistant
    id: homeassistant_time
    on_time:
      - seconds: 0
        minutes: /1
        then:
          - output.turn_on: LED
          - delay: 250ms
          - output.turn_off: LED

number:
  - platform: ld2420
    presence_timeout:
      name: Detection Presence Timeout
    min_gate_distance:
      name: Detection Gate Minimum
    max_gate_distance:
      name: Detection Gate Maximum
    # See "Number" section below for detail
    # gate_select:
    #   name: Select Gate to Set
    # still_threshold:
    #   name: Set Still Threshold Value
    # move_threshold:
    #   name: Set Move Threshold Value


###############################################################################
# HOME ASSISTANT BUTTONS ######################################################
###############################################################################

button:
  - platform: shutdown
    name: "Shutdown"
  - platform: restart
    name: "Restart"
  - platform: safe_mode
    name: "Restart (Safe Mode)"

  - platform: factory_reset
    disabled_by_default: True
    name: "Factory Reset ESP"
    id: factory_reset_all

  - platform: ld2420
    apply_config:
      name: Apply Config
    factory_reset:
      name: Factory Reset
    restart_module:
      name: Restart Module
    revert_config:
      name: Undo Edits

select:
  - platform: ld2420
    operating_mode:
      name: Operating Mode


###############################################################################
# SENSORS #####################################################################
###############################################################################

binary_sensor:
  - platform: template
    name: "TOF Near"
    id: tof_near
  - platform: template
    name: "TOF Mid"
    id: tof_mid

  - platform: ld2420
    has_target:
      name: Presence

###############################################################################

text_sensor:
  - platform: ld2420
    fw_version:
      name: LD2420 Firmware

###############################################################################

sensor:
  - platform: ld2420
    moving_distance:
      name : Moving Distance
      on_value_range:
        - above: 1
          below: 10
          then:
            - binary_sensor.template.publish:
                id: tof_near
                state: ON
            - binary_sensor.template.publish:
                id: tof_mid
                state: OFF
        - above: 10
          below: 30
          then:
            - binary_sensor.template.publish:
                id: tof_near
                state: OFF
            - binary_sensor.template.publish:
                id: tof_mid
                state: ON
        - above: 30
          then:
            - binary_sensor.template.publish:
                id: tof_near
                state: OFF
            - binary_sensor.template.publish:
                id: tof_mid
                state: OFF

    #Device UPTIME
  - platform: uptime
    name: Uptime
    id: sys_uptime
    update_interval: 60s

    #Device CPU Speed
  - platform: template
    name: "ESP Cpu Speed"
    accuracy_decimals: 0
    unit_of_measurement: Mhz
    lambda: |-
      return (id(cpu_speed));
    entity_category: "diagnostic"

    #Device Memory
  - platform: template
    id: esp_memory
    icon: mdi:memory
    name: ESP Free Memory
    lambda: return heap_caps_get_free_size(MALLOC_CAP_INTERNAL) / 1024;
    unit_of_measurement: "kB"
    state_class: measurement
    entity_category: "diagnostic"

    #Device RSSI
  - platform: wifi_signal
    name: RSSI
    id: wifi_signal_db
    update_interval: 60s
    entity_category: "diagnostic"

################################################################################

