###############################################################################
# BASE DEVICE CONFIG ##########################################################
###############################################################################

substitutions:
  name: m5stack-atom-echo-b70634
  friendly_name: Bedroom Atom Echo b70634
esphome:
  name: ${name}
  name_add_mac_suffix: false
  friendly_name: ${friendly_name}
esp32:
  board: m5stack-atom
  framework:
    type: arduino

################################################################################

# Wifi information
wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password
  ap:
    ssid: ${name}
    password: ${name}

# Enable Home Assistant API
api:
  encryption:
    key: u2TzqM15NfFCjK1tUO3HtM4LLPe38rO5T4YY67TYcT0=
ota:
  platform: esphome
  password: vCsLi39nZlYd96vt/aiuAWr8U2pTkeWXPsEx9RA3atI=

# Enable logging
logger:

###############################################################################
# INPUTS & OUTPUTS ############################################################
###############################################################################


###############################################################################
# HOME ASSISTANT BUTTONS ######################################################
###############################################################################

button:
  - platform: shutdown
    name: "Shutdown"
  - platform: restart
    name: "Restart"
  - platform: safe_mode
    name: "Restart (Safe Mode)"
