###############################################################################
# NOTES #######################################################################
###############################################################################

# https://fcc.report/FCC-ID/2BCBKTR4848/6883560.pdf

# NEEDS TO BE INITIALLY FLASHED VIA THE ESPHOME CLI, NOT THE WEB UI
# DISPLAY DRIVER (GC9503V) NOT CURRENTLY SUPPORTED BY ESPHOME (12/06/2024)

###############################################################################
# BASE DEVICE CONFIG ##########################################################
###############################################################################

substitutions:
  name: "panlee-bc02-eb14d4"
  friendly_name: PanLee BC02

esphome:
  name: ${name}
  friendly_name: ${friendly_name}
  name_add_mac_suffix: false
  platformio_options:
    board_build.flash_mode: dio

esp32:
  board: esp32-s3-devkitc-1
  variant: esp32s3
  framework:
    type: esp-idf
  flash_size: 16MB

psram:
  mode: octal
  speed: 80MHz

################################################################################

# Wifi information
wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password
  ap:
    ssid: ${name}
    password: ${name}

captive_portal:

api:

ota:
  platform: esphome

logger:
  hardware_uart: uart0

################################################################################


spi:
  clk_pin: GPIO45
  mosi_pin: GPIO48

###############################################################################
# HOME ASSISTANT BUTTONS ######################################################
###############################################################################

button:
  - platform: shutdown
    name: "Shutdown"
  - platform: restart
    name: "Restart"
  - platform: safe_mode
    name: "Restart (Safe Mode)"





# Example minimal configuration entry
display:
  - platform: ili9xxx
    model: GC9A01A
    dc_pin: GPIO38
    #reset_pin: GPIOXX
    show_test_card: true
    dimensions:
      height: 480
      width: 480
    lambda: |-
      it.fill(COLOR_BLACK);
