###############################################################################
# NOTES #######################################################################
###############################################################################

# https://www.waveshare.com/wiki/ESP32-S3-Zero
# https://files.waveshare.com/wiki/ESP32-S3-Zero/ESP32-S3-Zero-Sch.pdf


# https://www.aliexpress.com/item/1005005791515997.html
# Resolution:480*320
# Drive ic:ili9488

# 1 VCC power input (3.3V~5V)
# 2 GND power supply ground

# 3 CS LCD film selection - GPIO6 - Brown
# 4 RESET LCD reset - GPIO5 - Red
# 5 DC LCD bus command/data selection - GPIO4 - Orange
# 6 SDI (MoSi) LCD SPI display bus data input - GPIO3 - Yellow
# 7 SCK LCD SPI display bus clock signal - GPIO2 - Green
# 8 LED LCD backlight control (high level lighting) - GPIO7
# 9 SDO (MISO) LCD SPI display bus data input and output - GPIO1 - Blue

# 10 t _ clk SPI bus clock signal of touch panel
# 11 t _ cs Chip selection of SPI bus for touch panel
# 12 t _ din touch panel SPI bus data input
# 13 t _ do touch panel SPI bus data output
# 14 t _ IRQ touch panel interrupts IRQ signal.

###############################################################################
# BASE DEVICE CONFIG ##########################################################
###############################################################################

substitutions:
  name: waveshare-lcd-5b7094
  friendly_name: WaveShare LCD 5b7094

esphome:
  name: ${name}
  friendly_name: ${friendly_name}
  name_add_mac_suffix: false
  platformio_options:
    board_build.flash_mode: dio
  on_boot:
      priority: 200.0
      then:
        - component.update: lcd_display

esp32:
  board: esp32-s3-devkitc-1
  variant: esp32s3
  framework:
    type: esp-idf
    version: recommended
    sdkconfig_options:
      CONFIG_ESP32_S3_BOX_BOARD: "y"
   
psram:
  mode: quad
  speed: 80MHz


################################################################################

# Wifi information
wifi:
  ssid: DoceLar
  password: AnaPaul220309
  ap:
    ssid: ${name}
    password: ${name}

captive_portal:

# Enable Home Assistant API
api:
  encryption:
    key: "XbC7pgXBoGvZRAHQOmt1KSZOnKW+sYSlKd4aPu2tHPQ="
ota:
  platform: esphome

# Enable logging
logger:

###############################################################################
# INPUTS & OUTPUTS ############################################################
###############################################################################


###############################################################################
# VARIABLES & SCRIPTS #########################################################
###############################################################################

globals:
  - id: cpu_speed
    type: int
    restore_value: no
    initial_value: "0"


###############################################################################
# HOME ASSISTANT BUTTONS ######################################################
###############################################################################

button:
  - platform: shutdown
    name: "Shutdown"
  - platform: restart
    name: "Restart"
  - platform: safe_mode
    name: "Restart (Safe Mode)"

  - platform: factory_reset
    disabled_by_default: True
    name: "Factory Reset ESP"
    id: factory_reset_all

###############################################################################
# SENSORS #####################################################################
###############################################################################

#binary_sensor:


###############################################################################

#text_sensor:

###############################################################################

sensor:
    #Device UPTIME
  - platform: uptime
    name: Uptime
    id: sys_uptime
    update_interval: 60s

    #Device CPU Speed
  - platform: template
    name: "ESP Cpu Speed"
    accuracy_decimals: 0
    unit_of_measurement: Mhz
    lambda: |-
      return (id(cpu_speed));
    entity_category: "diagnostic"

    #Device Memory
  - platform: template
    id: esp_memory
    icon: mdi:memory
    name: ESP Free Memory
    lambda: return heap_caps_get_free_size(MALLOC_CAP_INTERNAL) / 1024;
    unit_of_measurement: "kB"
    state_class: measurement
    entity_category: "diagnostic"

    #Device RSSI
  - platform: wifi_signal
    name: RSSI
    id: wifi_signal_db
    update_interval: 60s
    entity_category: "diagnostic"

################################################################################
